n = input('Digite algo:')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços?', n.isspace())
print ('É alphanumérico?', n.isalnum())
print('É alfabético?', n.isalpha())
print('Está totalmente em letras maiusculas?', n.isupper())
print ('É um decimal?', n.isdecimal())
print('Está totalmente em minusculo?', n.islower())
print('É numérico?', n.isnumeric())
print('Está capitalizado?', n.istitle())